[package]
name = "metatablesnow/vision"
description = "A modern, lightweight command bar designed to feel native, intuitive, and powerful right out of the box"
license = "MIT"
authors = ["metatablesnow"]
version = "0.1.0"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
Fusion = "elttob/fusion@0.3.0"